// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALygu5HyhLGXsRBxUzsT-EcEwtsRuoec8',
    appId: '1:1057112917403:web:e4ef6a073fce59482d0d3e',
    messagingSenderId: '1057112917403',
    projectId: 'linchpin-369',
    authDomain: 'linchpin-369.firebaseapp.com',
    storageBucket: 'linchpin-369.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2NAmzkTLj6yykuiluuIFWFslgvZPGS-c',
    appId: '1:1057112917403:android:a97609948a4ec24f2d0d3e',
    messagingSenderId: '1057112917403',
    projectId: 'linchpin-369',
    storageBucket: 'linchpin-369.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZ2pCWHmP2T_59ov1w-M88PNvi9eTzUHE',
    appId: '1:1057112917403:ios:b0b50171ed5779a52d0d3e',
    messagingSenderId: '1057112917403',
    projectId: 'linchpin-369',
    storageBucket: 'linchpin-369.firebasestorage.app',
    iosBundleId: 'com.linchpinx.app.linchpinxApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZ2pCWHmP2T_59ov1w-M88PNvi9eTzUHE',
    appId: '1:1057112917403:ios:b0b50171ed5779a52d0d3e',
    messagingSenderId: '1057112917403',
    projectId: 'linchpin-369',
    storageBucket: 'linchpin-369.firebasestorage.app',
    iosBundleId: 'com.linchpinx.app.linchpinxApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALygu5HyhLGXsRBxUzsT-EcEwtsRuoec8',
    appId: '1:1057112917403:web:49689bca6ec9e4892d0d3e',
    messagingSenderId: '1057112917403',
    projectId: 'linchpin-369',
    authDomain: 'linchpin-369.firebaseapp.com',
    storageBucket: 'linchpin-369.firebasestorage.app',
  );
}
