name: Deploy Flutter PWA

on:
  push:
    branches:
      - v2

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            export PATH="$PATH:/opt/flutter/bin"  # Ensure Flutter is available
            cd /var/www/html
            
            if [ ! -d "flutter/.git" ]; then
              rm -rf flutter
              git clone https://github.com/Exir-world/linchpin_app.git flutter
            fi
            
            cd flutter
            git checkout v2
            git pull origin v2
            
            flutter build web
            rm -rf /var/www/html/pwa/*
            cp -r build/web/* /var/www/html/pwa
