name: Deploy Flutter PWA

on:
  push:
    branches:
      - v2

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}  # Use the GitHub Personal Access Token for authentication

      - name: Set up Flutter
        run: |
          if ! command -v flutter &> /dev/null; then
            echo "Flutter not found, installing..."
            git clone https://github.com/flutter/flutter.git /opt/flutter
            export PATH="$PATH:/opt/flutter/bin"
            echo 'export PATH="$PATH:/opt/flutter/bin"' >> ~/.bashrc
            source ~/.bashrc
          fi

      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Ensure we're in the right directory, or clone if not
            if [ ! -d "/var/www/html/pwa/.git" ]; then
              echo "Cloning repository..."
              git clone git@github.com:Exir-world/linchpin_app.git /var/www/html/pwa
            else
              cd /var/www/html/pwa && git pull origin v2
            fi

            # Install flutter if not present
            if ! command -v flutter &> /dev/null; then
              echo "Flutter not found, installing..."
              git clone https://github.com/flutter/flutter.git /opt/flutter
              export PATH="$PATH:/opt/flutter/bin"
              echo 'export PATH="$PATH:/opt/flutter/bin"' >> ~/.bashrc
              source ~/.bashrc
            fi

            # Build the Flutter web app
            flutter build web

            # Check if the build directory exists
            if [ -d "build/web" ]; then
              # Copy the build output to the target directory
              cp -r build/web/* /var/www/html/pwa
            else
              echo "Flutter build failed. No build/web directory found."
              exit 1
            fi
