name: Deploy Flutter PWA

on:
  push:
    branches:
      - v2

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}  # Use SSH key for authentication

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.0'

      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Ensure we're in the right directory, or clone if not
            cd /var/www/html/pwa || git clone git@github.com:Exir-world/linchpin_app.git /var/www/html/pwa
            git pull origin v2

            # Set up flutter if it's not installed
            if ! command -v flutter &> /dev/null; then
              echo "Flutter not found, installing..."
              # Add your install script here
            fi

            # Build the Flutter web app
            flutter build web

            # Copy the build output to the target directory
            cp -r build/web/* /var/www/html/pwa
